default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: <%= ENV['KAWAIII_JP_DEVELOPMENT_DATABASE_NAME'] %>
  host: <%= ENV['KAWAIII_JP_DEVELOPMENT_DATABASE_HOST'] %>
  username: <%= ENV['KAWAIII_JP_DEVELOPMENT_DATABASE_USERNAME'] %>
  password: <%= ENV['KAWAIII_JP_DEVELOPMENT_DATABASE_PASSWORD'] %>

test:
  <<: *default
  database: <%= ENV['KAWAIII_JP_TEST_DATABASE_NAME'] %>
  host: <%= ENV['KAWAIII_JP_TEST_DATABASE_HOST'] %>
  username: <%= ENV['KAWAIII_JP_TEST_DATABASE_USERNAME'] %>
  password: <%= ENV['KAWAIII_JP_TEST_DATABASE_PASSWORD'] %>

production:
  <<: *default
  database: <%= ENV['KAWAIII_JP_PRODUCTION_DATABASE_NAME'] %>
  host: <%= ENV['KAWAIII_JP_PRODUCTION_DATABASE_HOST'] %>
  username: <%= ENV['KAWAIII_JP_PRODUCTION_DATABASE_USERNAME'] %>
  password:  <%= ENV['KAWAIII_JP_PRODUCTION_DATABASE_PASSWORD'] %>
  #socket: /var/lib/mysql/mysql.sock

